# Generated by Django 5.2.16 on 2026-08-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
